// Vai em editor avançado e crie steps, separando todos por virgula
// nesse caso o parametro #"Language" precisa estar criado.
// ou voce pode criar um outro parametro para o suxifo, 
// isso facilitará na hora de criar o mesmo step em várias tabelas.


let
   Source = Excel.Workbook(File.Contents("C:\Users\ricardo.paula\Documents\RM\Gerdau\Amostra de Dados.xlsx"), null, true),
   Tabela = Source{[Item="d_Material",Kind="Table"]}[Data],

	Idioma =  if #"Language" = "Português"  then "pt" else
 				    if #"Language" = "English"    then "en" else
 				    if #"Language" = "Deutsche"   then "de" else
 				    if #"Language" = "Español"    then "es" else 
 				    "en",
            
    Coluna = "descr_material_" & Idioma,

    SelectCols 	= Table.SelectColumns(Tabela,{"Cod_material",Coluna}),
    RenameCols 	= Table.RenameColumns(SelectCols,{{Coluna,"Material"}})
in
    #"RenameCols"	
